//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsercizioEsame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestito
    {
        public int IdLibro { get; set; }
        public int Matricola { get; set; }
        public System.DateTime DataPrestito { get; set; }
        public Nullable<System.DateTime> DataScadenza { get; set; }
        public Nullable<System.DateTime> DataRestituzione { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Studente Studente { get; set; }
    }
}
